#!/bin/bash
# =====================================================
# LIFE DREAM BIG — one-command setup script
#
# Usage:
#   git pull origin main
#   bun run setup
#
# This script does EVERYTHING:
#   1. Creates .env from a hardcoded template (Supabase credentials
#      embedded — change them if you're not the original operator)
#   2. bun install
#   3. prisma generate  (rebuilds the client against the postgres schema)
#   4. prisma migrate deploy  (applies migrations — idempotent)
#   5. Starts the realtime mini-service in the background
#   6. Starts Next.js dev server in the foreground
#
# If you want production mode instead, run:
#   bun run setup:prod
# =====================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()  { echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARNING:${NC} $1"; }
err()  { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR:${NC} $1"; }
step() { echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"; echo -e "${BLUE}  $1${NC}"; echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"; }

# ---------- 1. Create .env if missing ----------
step "Step 1/6: Environment file (.env)"
if [ -f ".env" ]; then
    log ".env already exists — keeping it as-is"
    # Validate it has DATABASE_URL
    if ! grep -q "^DATABASE_URL=" .env || grep -q "^DATABASE_URL=\"\"$" .env; then
        err ".env exists but DATABASE_URL is empty or missing!"
        err "Please fix .env or delete it so this script can recreate it."
        exit 1
    fi
    # Validate it's postgres, not sqlite
    DB_URL_VAL=$(grep "^DATABASE_URL=" .env | head -1 | sed 's/^DATABASE_URL=//' | sed 's/^"//; s/"$//')
    if [[ "$DB_URL_VAL" == file:* ]]; then
        err ".env has DATABASE_URL pointing to SQLite (file:...). SQLite is NOT supported."
        err "Delete .env so this script can recreate it with Postgres credentials."
        exit 1
    fi
    log "DATABASE_URL is correctly a postgres:// URL"
else
    log "Creating .env with embedded Supabase credentials..."
    cat > .env <<'ENVEOF'
# =====================================================
# LIFE DREAM BIG — Clocking System — Environment
# =====================================================
# Auto-generated by scripts/setup.sh
# Credentials are for the operator's Supabase project.
# CHANGE AUTH_SECRET before real production use.

# ---------- Database (PostgreSQL — Supabase) ----------
# Pooled connection (PgBouncer transaction mode) — used by Prisma Client at runtime.
DATABASE_URL="postgres://postgres.amylsmqnhuvqqgajyxqr:Z6xondkYpjGOJR7M@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true"

# Direct connection (no pooler) — used by prisma migrate (DDL needs direct).
DIRECT_URL="postgres://postgres.amylsmqnhuvqqgajyxqr:Z6xondkYpjGOJR7M@aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require"

# ---------- Authentication ----------
# A long random secret for signing JWTs. Generate your own with:
#   openssl rand -base64 32
AUTH_SECRET="LIFEDB_PROD_AUTH_SECRET_2026_09_26_change_me_in_real_prod"

# NextAuth callback URL — required for credentials login to work.
NEXTAUTH_URL="http://localhost:3000"

# Public app URL.
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# ---------- Business config ----------
BUSINESS_TIMEZONE="America/New_York"
DEFAULT_HOURLY_RATE="5.00"

# ---------- Seed (initial admin) ----------
# These are only used by `bun run db:seed`. The database is already seeded.
SEED_ADMIN_EMAIL="bkencompanyy@gmail.com"
SEED_ADMIN_PASSWORD="wordpa$$123"
SEED_ADMIN_NAME="System Administrator"

# ---------- Seed (protected owner agent) — optional ----------
SEED_OWNER_EMAIL=""
SEED_OWNER_PASSWORD=""
SEED_OWNER_NAME="Owner"
SEED_OWNER_USERNAME="owner"
SEED_OWNER_EMPLOYEE_ID="OWNER-001"
SEED_OWNER_HOURLY_RATE="5.00"

# ---------- Realtime service ----------
REALTIME_SERVICE_URL="http://localhost:3003"
ENVEOF
    log ".env created with Supabase Postgres credentials"
fi

# ---------- 2. Install dependencies ----------
step "Step 2/6: Install dependencies (bun install)"
log "Running bun install..."
bun install 2>&1 | tail -3
log "Dependencies installed"

# ---------- 3. Generate Prisma client ----------
step "Step 3/6: Regenerate Prisma client"
log "This rebuilds node_modules/.prisma/client against the postgres schema..."
bunx prisma generate 2>&1 | tail -3
log "Prisma client generated"

# ---------- 4. Apply migrations ----------
step "Step 4/6: Apply database migrations"
log "Running prisma migrate deploy (idempotent — safe to re-run)..."
bunx prisma migrate deploy 2>&1 | tail -10
log "Migrations applied"

# ---------- 5. Start realtime mini-service ----------
step "Step 5/6: Start realtime mini-service (background)"

# Check if port 3003 is already in use
if command -v lsof >/dev/null 2>&1 && lsof -i :3003 >/dev/null 2>&1; then
    log "Port 3003 already in use — assuming realtime service is running"
else
    cd mini-services/realtime-service
    if [ ! -d "node_modules" ]; then
        log "Installing realtime service dependencies..."
        bun install 2>&1 | tail -3
    fi
    log "Starting realtime service on port 3003..."
    bun run dev > "$PROJECT_DIR/.zscripts/mini-service-realtime.log" 2>&1 &
    RT_PID=$!
    cd "$PROJECT_DIR"
    log "Realtime service started (PID: $RT_PID, log: .zscripts/mini-service-realtime.log)"

    # Wait for it to be ready
    for i in $(seq 1 10); do
        if curl -s --connect-timeout 1 http://localhost:3003/health >/dev/null 2>&1; then
            log "Realtime service is ready"
            break
        fi
        sleep 1
    done
fi

# ---------- 6. Start Next.js dev server ----------
step "Step 6/6: Start Next.js dev server (foreground)"

# Cleanup function — kill the realtime service when this script exits
cleanup() {
    if [ -n "${RT_PID:-}" ] && kill -0 "$RT_PID" 2>/dev/null; then
        log "Stopping realtime service (PID: $RT_PID)..."
        kill "$RT_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

log "Starting Next.js on http://localhost:3000"
log ""
log "═══════════════════════════════════════════════════════════════"
log "  LIFE DREAM BIG — Clocking System is starting..."
log ""
log "  Login URLs:"
log "    Agent:  http://localhost:3000/connexion"
log "            (bken / wordpa\$\$123  OR  bkencompanyy@gmail.com / wordpa\$\$123)"
log ""
log "    Admin:  http://localhost:3000/connexion"
log "            (admin / ChangeMe!2025)"
log ""
log "  Press Ctrl+C to stop all services"
log "═══════════════════════════════════════════════════════════════"
log ""

# Run Next.js in the foreground so it receives Ctrl+C
exec bun run dev
